"""Base production schema

Revision ID: 2ae4be61eb25
Revises:
Create Date: 2026-01-25 17:00:17.600334

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2ae4be61eb25"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Extensions for Production (Postgres)
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
        op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")

    op.create_table(
        "education_normalization",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("raw_value", sa.String(length=120), nullable=False),
        sa.Column("normalized_value", sa.String(length=120), nullable=False),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_education_normalization_normalized_value"),
        "education_normalization",
        ["normalized_value"],
        unique=False,
    )
    op.create_index(
        op.f("ix_education_normalization_raw_value"),
        "education_normalization",
        ["raw_value"],
        unique=True,
    )
    op.create_table(
        "location",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("raw", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "metrics_daily",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("role_family", sa.String(length=120), nullable=True),
        sa.Column("location_key", sa.String(length=120), nullable=True),
        sa.Column("postings", sa.Integer(), nullable=False),
        sa.Column("salary_p50", sa.Float(), nullable=True),
        sa.Column("tenure_mix_json", sa.JSON(), nullable=False),
        sa.Column("top_skills_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_metrics_daily_date"), "metrics_daily", ["date"], unique=False
    )
    op.create_index(
        op.f("ix_metrics_daily_location_key"),
        "metrics_daily",
        ["location_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metrics_daily_role_family"),
        "metrics_daily",
        ["role_family"],
        unique=False,
    )
    op.create_table(
        "organization",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("ats", sa.String(length=100), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organization_name"), "organization", ["name"], unique=True)
    op.create_table(
        "processing_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("process_type", sa.String(length=120), nullable=False),
        sa.Column("results", sa.JSON(), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_processing_log_process_type"),
        "processing_log",
        ["process_type"],
        unique=False,
    )
    op.create_table(
        "role_evolution",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title_norm", sa.String(length=120), nullable=False),
        sa.Column("month", sa.DateTime(), nullable=False),
        sa.Column("top_skills", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_role_evolution_month"), "role_evolution", ["month"], unique=False
    )
    op.create_index(
        op.f("ix_role_evolution_title_norm"),
        "role_evolution",
        ["title_norm"],
        unique=False,
    )
    op.create_table(
        "skill",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("taxonomy_ref", sa.String(length=120), nullable=True),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skill_name"), "skill", ["name"], unique=True)
    op.create_table(
        "skill_trends_monthly",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("skill", sa.String(length=120), nullable=False),
        sa.Column("title_norm", sa.String(length=120), nullable=False),
        sa.Column("month", sa.DateTime(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("share", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_skill_trends_monthly_month"),
        "skill_trends_monthly",
        ["month"],
        unique=False,
    )
    op.create_index(
        op.f("ix_skill_trends_monthly_skill"),
        "skill_trends_monthly",
        ["skill"],
        unique=False,
    )
    op.create_index(
        op.f("ix_skill_trends_monthly_title_norm"),
        "skill_trends_monthly",
        ["title_norm"],
        unique=False,
    )
    op.create_table(
        "title_adjacency",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title_a", sa.String(length=120), nullable=False),
        sa.Column("title_b", sa.String(length=120), nullable=False),
        sa.Column("similarity", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_title_adjacency_title_a"), "title_adjacency", ["title_a"], unique=False
    )
    op.create_index(
        op.f("ix_title_adjacency_title_b"), "title_adjacency", ["title_b"], unique=False
    )
    op.create_table(
        "title_norm",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("family", sa.String(length=120), nullable=False),
        sa.Column("canonical_title", sa.String(length=120), nullable=False),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_title_norm_canonical_title"),
        "title_norm",
        ["canonical_title"],
        unique=False,
    )
    op.create_index(
        op.f("ix_title_norm_family"), "title_norm", ["family"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("whatsapp_number", sa.String(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("subscription_tier", sa.String(length=50), nullable=False),
        sa.Column("subscription_expires", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_uuid"), "users", ["uuid"], unique=True)
    op.create_table(
        "company_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("overall_rating", sa.Float(), nullable=False),
        sa.Column("work_life_balance", sa.Float(), nullable=True),
        sa.Column("compensation", sa.Float(), nullable=True),
        sa.Column("career_growth", sa.Float(), nullable=True),
        sa.Column("management", sa.Float(), nullable=True),
        sa.Column("culture", sa.Float(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("review_text", sa.Text(), nullable=False),
        sa.Column("pros", sa.Text(), nullable=True),
        sa.Column("cons", sa.Text(), nullable=True),
        sa.Column("advice_to_management", sa.Text(), nullable=True),
        sa.Column("job_title", sa.String(length=255), nullable=True),
        sa.Column("employment_status", sa.String(length=50), nullable=True),
        sa.Column("employment_duration", sa.String(length=100), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_anonymous", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.Column("moderation_notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job_alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("query", sa.String(length=500), nullable=False),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("frequency", sa.String(length=50), nullable=False),
        sa.Column("delivery_methods", sa.JSON(), nullable=False),
        sa.Column("jobs_found_total", sa.Integer(), nullable=False),
        sa.Column("last_triggered", sa.DateTime(), nullable=True),
        sa.Column("last_jobs_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job_post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("url_hash", sa.String(length=32), nullable=True),
        sa.Column("first_seen", sa.DateTime(), nullable=False),
        sa.Column("last_seen", sa.DateTime(), nullable=False),
        sa.Column("repost_count", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=True),
        sa.Column("title_raw", sa.String(length=255), nullable=False),
        sa.Column("title_norm_id", sa.Integer(), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("tenure", sa.String(length=50), nullable=True),
        sa.Column("salary_min", sa.Float(), nullable=True),
        sa.Column("salary_max", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("seniority", sa.String(length=50), nullable=True),
        sa.Column("description_raw", sa.Text(), nullable=True),
        sa.Column("description_clean", sa.Text(), nullable=True),
        sa.Column("requirements_raw", sa.Text(), nullable=True),
        sa.Column("education", sa.String(length=120), nullable=True),
        sa.Column("attachment_flag", sa.Boolean(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["title_norm_id"],
            ["title_norm.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index(
        op.f("ix_job_post_url_hash"), "job_post", ["url_hash"], unique=False
    )
    op.create_table(
        "search_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("query", sa.String(length=500), nullable=False),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.Column("results_count", sa.Integer(), nullable=False),
        sa.Column("clicked_jobs", sa.JSON(), nullable=False),
        sa.Column("searched_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_search_history_searched_at"),
        "search_history",
        ["searched_at"],
        unique=False,
    )
    op.create_table(
        "skill_assessments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("level", sa.String(length=50), nullable=False),
        sa.Column("percentile", sa.Float(), nullable=True),
        sa.Column("assessment_type", sa.String(length=50), nullable=False),
        sa.Column("questions_total", sa.Integer(), nullable=False),
        sa.Column("questions_correct", sa.Integer(), nullable=False),
        sa.Column("time_taken_minutes", sa.Integer(), nullable=True),
        sa.Column("is_certified", sa.Boolean(), nullable=False),
        sa.Column("certificate_url", sa.String(length=500), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("taken_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skill.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_user_skill_assessment",
        "skill_assessments",
        ["user_id", "skill_id"],
        unique=False,
    )
    op.create_table(
        "user_analytics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("event_data", sa.JSON(), nullable=False),
        sa.Column("page_url", sa.String(length=500), nullable=True),
        sa.Column("referrer", sa.String(length=500), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_analytics_timestamp"),
        "user_analytics",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "user_notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("delivered_via", sa.JSON(), nullable=False),
        sa.Column("delivery_status", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_notifications_created_at"),
        "user_notifications",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "user_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("current_role", sa.String(length=255), nullable=True),
        sa.Column("experience_level", sa.String(length=50), nullable=True),
        sa.Column("education", sa.Text(), nullable=True),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("career_goals", sa.Text(), nullable=True),
        sa.Column("preferred_locations", sa.JSON(), nullable=False),
        sa.Column("salary_expectations", sa.JSON(), nullable=False),
        sa.Column("job_alert_preferences", sa.JSON(), nullable=False),
        sa.Column("notification_preferences", sa.JSON(), nullable=False),
        sa.Column("privacy_settings", sa.JSON(), nullable=False),
        sa.Column("profile_completeness", sa.Float(), nullable=False),
        sa.Column("cv_data", sa.JSON(), nullable=False),
        sa.Column("linkedin_url", sa.String(length=500), nullable=True),
        sa.Column("portfolio_url", sa.String(length=500), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "job_applications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("job_post_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("applied_at", sa.DateTime(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.Column("cover_letter", sa.Text(), nullable=True),
        sa.Column("cv_version", sa.String(length=100), nullable=True),
        sa.Column("application_source", sa.String(length=100), nullable=True),
        sa.Column("referrer_info", sa.JSON(), nullable=False),
        sa.Column("interview_dates", sa.JSON(), nullable=False),
        sa.Column("feedback_received", sa.Text(), nullable=True),
        sa.Column("salary_offered", sa.JSON(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_post_id"],
            ["job_post.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_user_job_application",
        "job_applications",
        ["user_id", "job_post_id"],
        unique=True,
    )
    op.create_table(
        "job_dedupe_map",
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("canonical_job_id", sa.Integer(), nullable=False),
        sa.Column("similarity_score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_job_id"],
            ["job_post.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job_post.id"],
        ),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_index(
        op.f("ix_job_dedupe_map_canonical_job_id"),
        "job_dedupe_map",
        ["canonical_job_id"],
        unique=False,
    )
    op.create_table(
        "job_embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("vector_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job_post.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job_entities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("entities", sa.JSON(), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("tools", sa.JSON(), nullable=False),
        sa.Column("education", sa.JSON(), nullable=False),
        sa.Column("experience", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job_post.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id"),
    )
    op.create_table(
        "job_skill",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_post_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_post_id"],
            ["job_post.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skill.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "saved_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("job_post_id", sa.Integer(), nullable=False),
        sa.Column("saved_at", sa.DateTime(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("folder", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_post_id"],
            ["job_post.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_user_job_saved", "saved_jobs", ["user_id", "job_post_id"], unique=True
    )
    op.create_table(
        "user_job_recommendations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("job_post_id", sa.Integer(), nullable=False),
        sa.Column("match_score", sa.Float(), nullable=False),
        sa.Column("skill_match_score", sa.Float(), nullable=False),
        sa.Column("location_match_score", sa.Float(), nullable=False),
        sa.Column("salary_match_score", sa.Float(), nullable=False),
        sa.Column("experience_match_score", sa.Float(), nullable=False),
        sa.Column("match_explanation", sa.Text(), nullable=True),
        sa.Column("missing_skills", sa.JSON(), nullable=False),
        sa.Column("matching_skills", sa.JSON(), nullable=False),
        sa.Column("recommended_at", sa.DateTime(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("viewed", sa.Boolean(), nullable=False),
        sa.Column("clicked", sa.Boolean(), nullable=False),
        sa.Column("dismissed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_post_id"],
            ["job_post.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_user_job_recommendation",
        "user_job_recommendations",
        ["user_id", "job_post_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_user_job_recommendations_recommended_at"),
        "user_job_recommendations",
        ["recommended_at"],
        unique=False,
    )
    op.create_table(
        "interview_preparations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("job_application_id", sa.Integer(), nullable=True),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("role_title", sa.String(length=255), nullable=False),
        sa.Column("interview_type", sa.String(length=50), nullable=False),
        sa.Column("scheduled_date", sa.DateTime(), nullable=True),
        sa.Column("questions_practiced", sa.JSON(), nullable=False),
        sa.Column("research_notes", sa.Text(), nullable=True),
        sa.Column("preparation_score", sa.Float(), nullable=True),
        sa.Column("suggested_questions", sa.JSON(), nullable=False),
        sa.Column("company_insights", sa.JSON(), nullable=False),
        sa.Column("role_specific_tips", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_application_id"],
            ["job_applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("interview_preparations")
    op.drop_index(
        op.f("ix_user_job_recommendations_recommended_at"),
        table_name="user_job_recommendations",
    )
    op.drop_index("idx_user_job_recommendation", table_name="user_job_recommendations")
    op.drop_table("user_job_recommendations")
    op.drop_index("idx_user_job_saved", table_name="saved_jobs")
    op.drop_table("saved_jobs")
    op.drop_table("job_skill")
    op.drop_table("job_entities")
    op.drop_table("job_embeddings")
    op.drop_index(
        op.f("ix_job_dedupe_map_canonical_job_id"), table_name="job_dedupe_map"
    )
    op.drop_table("job_dedupe_map")
    op.drop_index("idx_user_job_application", table_name="job_applications")
    op.drop_table("job_applications")
    op.drop_table("user_profiles")
    op.drop_index(
        op.f("ix_user_notifications_created_at"), table_name="user_notifications"
    )
    op.drop_table("user_notifications")
    op.drop_index(op.f("ix_user_analytics_timestamp"), table_name="user_analytics")
    op.drop_table("user_analytics")
    op.drop_index("idx_user_skill_assessment", table_name="skill_assessments")
    op.drop_table("skill_assessments")
    op.drop_index(op.f("ix_search_history_searched_at"), table_name="search_history")
    op.drop_table("search_history")
    op.drop_index(op.f("ix_job_post_url_hash"), table_name="job_post")
    op.drop_table("job_post")
    op.drop_table("job_alerts")
    op.drop_table("company_reviews")
    op.drop_index(op.f("ix_users_uuid"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_title_norm_family"), table_name="title_norm")
    op.drop_index(op.f("ix_title_norm_canonical_title"), table_name="title_norm")
    op.drop_table("title_norm")
    op.drop_index(op.f("ix_title_adjacency_title_b"), table_name="title_adjacency")
    op.drop_index(op.f("ix_title_adjacency_title_a"), table_name="title_adjacency")
    op.drop_table("title_adjacency")
    op.drop_index(
        op.f("ix_skill_trends_monthly_title_norm"), table_name="skill_trends_monthly"
    )
    op.drop_index(
        op.f("ix_skill_trends_monthly_skill"), table_name="skill_trends_monthly"
    )
    op.drop_index(
        op.f("ix_skill_trends_monthly_month"), table_name="skill_trends_monthly"
    )
    op.drop_table("skill_trends_monthly")
    op.drop_index(op.f("ix_skill_name"), table_name="skill")
    op.drop_table("skill")
    op.drop_index(op.f("ix_role_evolution_title_norm"), table_name="role_evolution")
    op.drop_index(op.f("ix_role_evolution_month"), table_name="role_evolution")
    op.drop_table("role_evolution")
    op.drop_index(op.f("ix_processing_log_process_type"), table_name="processing_log")
    op.drop_table("processing_log")
    op.drop_index(op.f("ix_organization_name"), table_name="organization")
    op.drop_table("organization")
    op.drop_index(op.f("ix_metrics_daily_role_family"), table_name="metrics_daily")
    op.drop_index(op.f("ix_metrics_daily_location_key"), table_name="metrics_daily")
    op.drop_index(op.f("ix_metrics_daily_date"), table_name="metrics_daily")
    op.drop_table("metrics_daily")
    op.drop_table("location")
    op.drop_index(
        op.f("ix_education_normalization_raw_value"),
        table_name="education_normalization",
    )
    op.drop_index(
        op.f("ix_education_normalization_normalized_value"),
        table_name="education_normalization",
    )
    op.drop_table("education_normalization")
    # ### end Alembic commands ###
